### ISSUE TITLE
Modal - React Router implementation

### ISSUE THREAD

**Issue by amarmechai** [nichitaa/auth-react-router#10]
can we integrate **Modal routes** with this project?

**Reference** : [Create contextual modal navigation with React Router V6](https://dev.to/devmdmamun/create-contextual-modal-navigation-with-react-router-v6-28k2)

**IRoute**

``` ts
export interface IRoute {
  ...

  modal?: boolean;
}
```

**We can use this method de get all modal routes**
``` js
const getModalRoutes = (routes: IRoute[]) => {
  return routes
    .map(route => {
      let modalRooutes: IRoute[] = [];
      const { children, ...rest } = route;

      if (rest.modal)
        modalRooutes.push(rest);

      if (children)
        modalRooutes.push(...getModalRoutes(children));

      return modalRooutes;
    })
    .reduce((accumulator, value) => accumulator.concat(value), []);
}
```

**Comment by nichitaa** [comment]
Hi @amarmechai, I think it is possible to do so, if it is urgent you could open a PR, as I would have some time only at the end of the week to see how to implement it.
* But isn't it possible to achieve with query params (to show/close modal) ?

* As well from the first look, there is a possibility that the use of `useLocation` hook at the root of our `App` component would trigger re-renders whenever page changes, which would force all `Route` components to re-render, (if there would be common layout with some `Outlet`s component, layout would probably re-render, even if it'd be common for a single `Route`)
```js
const location = useLocation();
```

**Comment by amarmechai** [comment]
Hi @nichitaa, thank you for the answer.
With query params, it should be possible :thinking: !
